source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'RickyMoney' do
    
pod 'DGActivityIndicatorView'
pod 'Parse'
pod 'LMDropdownView'
pod 'THPinViewController'
pod 'JTCalendar', '~> 2.0'
pod 'UNAlertView'

end