source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'RickyMoney' do
    
    pod 'DGActivityIndicatorView'
    pod 'LMDropdownView'
    pod 'Firebase', '>= 2.5.1'

end